apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth-auth
spec:
  forwardAuth:
    address: "http://oauth2-proxy.oauth2-proxy.svc.cluster.local.:80/oauth2/"
    trustForwardHeader: true
    authResponseHeaders:
    - "X-Auth-Request-Email"
    - "X-Auth-Request-User"
    - "Set-Cookie"
