apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  timeout.reconciliation: 60s
  cluster.inClusterEnabled: "false"
  url: "https://argocd.infra.bennaylor.dev"
  dex.config: |-
    connectors: []
  # --load-restrictor:
  #   For being able to refer 'base/backend_filestore.yaml' from the prod overlay
  #   This can be removed when we start using Argo CD for Prod deployments
  # --enable-alpha-plugins, --enable-exec
  #   Used for kustomize with ksops
  kustomize.buildOptions: "--load-restrictor LoadRestrictionsNone --enable-alpha-plugins --enable-exec"
  application.resourceTrackingMethod: annotation
