apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  cluster.inClusterEnabled: "false"
  url: "https://argocd.bennaylor.dev"
  # --load-restrictor:
  #   For being able to refer 'base/backend_filestore.yaml' from the prod overlay
  #   This can be removed when we start using Argo CD for Prod deployments
  # --enable-alpha-plugins, --enable-exec
  #   Used for kustomize with ksops
  kustomize.buildOptions: "--load-restrictor LoadRestrictionsNone --enable-alpha-plugins --enable-exec"
  application.resourceTrackingMethod: annotation
  exec.enabled: "true"
  # re-include endpointslice mapping
  resource.exclusions: |
    ### Network resources created by the Kubernetes control plane and excluded to reduce the number of watched events and UI clutter
    - apiGroups:
      - ''
      - discovery.k8s.io
      kinds:
      - Endpoints
      # - EndpointSlice
    ### Internal Kubernetes resources excluded reduce the number of watched events
    - apiGroups:
      - coordination.k8s.io
      kinds:
      - Lease
    ### Internal Kubernetes Authz/Authn resources excluded reduce the number of watched events
    - apiGroups:
      - authentication.k8s.io
      - authorization.k8s.io
      kinds:
      - SelfSubjectReview
      - TokenReview
      - LocalSubjectAccessReview
      - SelfSubjectAccessReview
      - SelfSubjectRulesReview
      - SubjectAccessReview
    ### Intermediate Certificate Request excluded reduce the number of watched events
    - apiGroups:
      - certificates.k8s.io
      kinds:
      - CertificateSigningRequest
    - apiGroups:
      - cert-manager.io
      kinds:
      - CertificateRequest
    ### Cilium internal resources excluded reduce the number of watched events and UI Clutter
    - apiGroups:
      - cilium.io
      kinds:
      - CiliumIdentity
      - CiliumEndpoint
      - CiliumEndpointSlice
    ### Kyverno intermediate and reporting resources excluded reduce the number of watched events and improve performance
    - apiGroups:
      - kyverno.io
      - reports.kyverno.io
      - wgpolicyk8s.io
      kinds:
      - PolicyReport
      - ClusterPolicyReport
      - EphemeralReport
      - ClusterEphemeralReport
      - AdmissionReport
      - ClusterAdmissionReport
      - BackgroundScanReport
      - ClusterBackgroundScanReport
      - UpdateRequest
  dex.config: |-
    connectors:
    - type: oidc
      id: bramble
      name: bennaylor.dev
      config:
        issuer: https://keycloak.bennaylor.dev/realms/master
        clientID: $argocd-dex-credentials:DEX_BRAMBLE_CLIENT_ID
        clientSecret: $argocd-dex-credentials:DEX_BRAMBLE_CLIENT_SECRET
        redirectURI: https://argocd.bennaylor.dev/api/dex/callback
        scopes:
        - profile
        - groups
        - email
        insecureEnableGroups: true
        claimMapping:
          groups: "groups"
    - type: oidc
      id: twk3s
      name: Techwerkers
      config:
        issuer: https://id.techwerkers.nl/realms/techwerkers
        clientID: $argocd-dex-credentials:DEX_TWK3S_CLIENT_ID
        clientSecret: $argocd-dex-credentials:DEX_TWK3S_CLIENT_SECRET
        redirectURI: https://argocd.bennaylor.dev/api/dex/callback
        scopes:
        - profile
        - groups
        - email
        insecureEnableGroups: true
        claimMapping:
          groups: "groups"
