apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  timeout.reconciliation: 60s
  cluster.inClusterEnabled: "false"
  url: "https://argocd.bennaylor.dev"
  # --load-restrictor:
  #   For being able to refer 'base/backend_filestore.yaml' from the prod overlay
  #   This can be removed when we start using Argo CD for Prod deployments
  # --enable-alpha-plugins, --enable-exec
  #   Used for kustomize with ksops
  kustomize.buildOptions: "--load-restrictor LoadRestrictionsNone --enable-alpha-plugins --enable-exec"
  application.resourceTrackingMethod: annotation
  dex.config: |-
    connectors:
    - type: oidc
      id: bramble
      name: bennaylor.dev
      config:
        issuer: https://keycloak.bennaylor.dev/realms/master
        clientID: $argocd-dex-credentials:DEX_BRAMBLE_CLIENT_ID
        clientSecret: $argocd-dex-credentials:DEX_BRAMBLE_CLIENT_SECRET
        redirectURI: https://argocd.platform.instruqt.net/api/dex/callback
