apiVersion: v1
kind: Secret
metadata:
    name: docker-hub
    namespace: kargo-shared-resources
    labels:
        kargo.akuity.io/cred-type: image
type: Opaque
stringData:
    repoURL: ENC[AES256_GCM,data:PZMG6do2RCUORlq+bHuxYBBR+FU9m/lIZfH+g5A=,iv:C8DNBk4HB6ZeGFdFaB0x7ZylF2dj0QrHIi9Y+3kZ+9M=,tag:E2V1mP7DoxUKnS2g6LHpTA==,type:str]
    repoURLIsRegex: ENC[AES256_GCM,data:58T4Uw==,iv:IYc3w/nhS11wvyAAHaU+yMjYsrMA3OF1FV7/xoGOheM=,tag:5CSuKyyszEeeBWFoUSHr4Q==,type:str]
    username: ENC[AES256_GCM,data:u2ezSyoXuTbJ,iv:4O1fflryKqA9amyt4/ZrgaetePLGPkFHh5z1uWHZsWo=,tag:dP3vMKATk+/Mt283QQfbEg==,type:str]
    password: ENC[AES256_GCM,data:UAs4Xd1wSzIxbOn7BVLGaWj24XJyuTxWt8bdkm4j8suVVunQ,iv:g8IHMWTL39IcTb3RBRqb3d8qvbCH1XStf8NQyD/0gxI=,tag:cNshYe0q7/XhZ7umTk5xBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RHB5VUYwQ1BDTldQSXBz
            RlJOeW1JSHVVRXJBUXQ4d3hBbktuTk1OeUJjCjlVbDJCNzltU2hJZGFMWGxLTWw4
            QlYzd3JaOHF3djVmWlIxTUNYeW96cjgKLS0tIGZnWmVNMGZuRXBKNVpYRTF1VzUx
            dUNoOGVBRWlLeENoRXlMNjRkcGJrWWcKt+MX9TyCrwOaD9u+eLaDgVOpdo/Dl+wc
            3qvpjngddSoivFCd0crydnvWUtskAbTxffrHXi/TSs+70LIaugQYGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWDZJRVdhM3hQWUNxdWMy
            b1dPTER2MUlaMlRKWjU4dk1mOWdkMlpJT0djCkRNUS95WlRuSlNKWXQyNkcvcnV6
            YmlyRUdkUzBFNDgyS0RtaW5qZTcwZmMKLS0tIG5FV0hVSmxvVjQ0bTBqUUJ1bnNH
            NVp0T3ROb2hzTkFMcExKYU5Rbk9ERHMK97cvElq0jBx46ZsH8iOlo3vMjuowB8/u
            MrGNPKrlw1lmZ7h/y70xXSX5h7F0fwb6HbWKi0T0dFwTysTSJxcqvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rt8t5r7qv3lqad907pxg9233x2xlvr5kvqc8tj38y560ayd8ruhq352jgy
    lastmodified: "2026-08-31T12:40:25Z"
    mac: ENC[AES256_GCM,data:Vq3jD0yCVWHZ/6eki8nIe9ZLUL+DAbrDC4utjMwz61sf7Kc0AxZAP9TT8P+ObfIVdeTd266CBz+poqD1/5WJactOA0AebpTvv+ie2bKbPkEFL77opCfrCBXy85VkC/51lZjaMoGYz+aOliaT3eTqprSuvZ17wlCeWKyc9YsXZkA=,iv:+dKxKAge3PgHIZe+Al4m2hQq1tyDwTwmbOudtpqrj/c=,tag:PI1ruWhZFF9PXtJM40IliQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
