apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bramble-root-kargo
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/b-n/bramble.git
      revision: main
      directories:
      - path: adguard
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: "bramble-{{ .path.basename }}"
      annotations:
        kargo.akuity.io/authorized-stage: kp-bramble:live-{{ .path.basename }}
    spec:
      project: bramble
      source:
        repoURL: https://github.com/b-n/bramble.git
        targetRevision: kargo-bramble-{{ .path.basename }}
        path: "{{ .path.path }}"
      destination:
        name: bramble
        namespace: "{{ .path.basename }}"
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
        - FailOnSharedResource=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
  ignoreApplicationDifferences:
  - jsonPointers:
    - /spec/source/targetRevision
    - /spec/syncPolicy/automated
