apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bramble-root
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/b-n/bramble.git
      revision: main
      directories:
      # ArgoCD is manually applied
      # - path: argocd
      - path: adguard
      - path: arr
      - path: cert-manager
      - path: headscale
      - path: homeassistant
      - path: immich
      - path: infra
      - path: keycloak
      - path: n8n
      - path: oauth2-proxy
      - path: observability
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: "bramble-{{ .path.basename }}"
    spec:
      project: bramble
      source:
        repoURL: https://github.com/b-n/bramble.git
        targetRevision: main
        path: "{{ .path.path }}"
      destination:
        name: bramble
        namespace: "{{ .path.basename }}"
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
        - FailOnSharedResource=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
  ignoreApplicationDifferences:
  - jsonPointers:
    - /spec/source/targetRevision
