apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: oauth2-proxy-callbacks
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: adguard
  to:
  - group: ""
    kind: Service
