apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-keycloak
    namespace: oauth2-proxy
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:L3UydWs9Yg==,iv:ag/lpFIqoQ7Yf80lNOj+SnmQ2an3hZD0aBPuk8W0tc8=,tag:KP/m+lTvwrVRzWmaKDJfHA==,type:str]
    client-secret: ENC[AES256_GCM,data:1a/AkshwiMW/Kx3t1Rp6i7yn0Kak96XZrJkExKS/OkY=,iv:M+qdEeeOUd10OmTuCrbB2zgmNmaxEuTGLoaPjM+jHXw=,tag:oWgoam64i/QFGEYNuu/wdQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:OO+WppOEqsPriEu3Apy8mS/9vEdm6nAUZgHISgd3QRA=,iv:bC9lYxUtQIcWWOSw0CU9ld0HYXISQNaDQCQ9LgS92BU=,tag:yLbT1EQhAeOzWPzAxTSziA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcXJseFc4QXUyME5EVTRK
            clYxeFdjbGtUaCtkSkl1b3RTS09halI1dGp3CnQ1V3NzUVpYdHBTdEJqaEZEV1dD
            cXFvMUg0ZVI4YkZDRzJSb0djUk93SFkKLS0tIGx0U3pGR0s2VXZYMnBPYlFTQnNV
            UVRqUlNDSVZaODNaKzByZGE0WnBQbGMKJr62fDxWVt+R4HqTwRJydds2xK1cM8Tb
            ncaEaUUoPCb0FZwvgdK2oMFErAWa3IUFzSLMNVj4s0p7cpSn9gdQtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVG5GSUJ5RzVRRHdSVFF4
            RTJJc3lnc25Vd0V3NUMxZ0Q5enV3UGJabkJBCk84bmJ6WnZYcmVEd2dUQjd3SWV0
            TVV1K2U2bUFXZitJLzk2ckEyQU91Uk0KLS0tIHkxQTBQcER0RnJxamE5enIrdjh5
            Sm53Zjd2VGJZTXNZbEpJWjIyWUZta2cKD57qgmKwPqivdNhAuG628bDug4H3lgpM
            qcU5VQep/1mvqDzEOGKqcuck6be97ofW4RhNLtDQHrR3ZpQETkIbgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rt8t5r7qv3lqad907pxg9233x2xlvr5kvqc8tj38y560ayd8ruhq352jgy
    lastmodified: "2026-03-15T11:44:40Z"
    mac: ENC[AES256_GCM,data:MLfnoKpDbuRtTo1bqIfx3xKEWHpZeuH+t89C3quTYfmMxam0r49bGDwH490RtGC3PE1bJ6vnP6+FELThzPAkqJh+T+xi6CTjowTPaKNO3WaW7BwarnIB9jGHpOXR2XTdAFLtk9+zFA13mhmy+yR8MDGf217NsLbM7FLfuiDb8n0=,iv:1J24iAHswb1L4Gv9tcDEA3+JDgu9/qNtBnfHilKGbfM=,tag:5wcKgjrtZ+y++uux9zE0sA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
