apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-keycloak
    namespace: oauth2-proxy
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:L3UydWs9Yg==,iv:ag/lpFIqoQ7Yf80lNOj+SnmQ2an3hZD0aBPuk8W0tc8=,tag:KP/m+lTvwrVRzWmaKDJfHA==,type:str]
    client-secret: ENC[AES256_GCM,data:1a/AkshwiMW/Kx3t1Rp6i7yn0Kak96XZrJkExKS/OkY=,iv:M+qdEeeOUd10OmTuCrbB2zgmNmaxEuTGLoaPjM+jHXw=,tag:oWgoam64i/QFGEYNuu/wdQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:OO+WppOEqsPriEu3Apy8mS/9vEdm6nAUZgHISgd3QRA=,iv:bC9lYxUtQIcWWOSw0CU9ld0HYXISQNaDQCQ9LgS92BU=,tag:yLbT1EQhAeOzWPzAxTSziA==,type:str]
sops:
    age:
        - recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNmc0R2Q3QlhWRXBDbjVO
            L3dzVlZpaVIyNUsxR3V3RHE1NTdNTlVTcFEwCmVzbWgxMDl2aHRGYVoxM09DN1lp
            YzdBWDQwUVpNMG42Q3R0bXh1QWlNY3cKLS0tIG8rZ1h4OHFaTDhKZ0o1djZJbE9V
            cU13NG5BT0d2eTFKTmM5QzRuVGtmL0EKGnzbTgvNOnc9zyihWUlYMGB2zBRPdRzv
            kHxNEpL+XCDVKfjuHzBPqijfxNoVkJI1zrkVkkNe4JP+NsqS8+G8NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T11:44:40Z"
    mac: ENC[AES256_GCM,data:MLfnoKpDbuRtTo1bqIfx3xKEWHpZeuH+t89C3quTYfmMxam0r49bGDwH490RtGC3PE1bJ6vnP6+FELThzPAkqJh+T+xi6CTjowTPaKNO3WaW7BwarnIB9jGHpOXR2XTdAFLtk9+zFA13mhmy+yR8MDGf217NsLbM7FLfuiDb8n0=,iv:1J24iAHswb1L4Gv9tcDEA3+JDgu9/qNtBnfHilKGbfM=,tag:5wcKgjrtZ+y++uux9zE0sA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
