apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-dex
    namespace: oauth2-proxy
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:RrGn39DXZN2HV0ccEA==,iv:3Bis4AtV4xWI1KQ1Aj6FThNkFnRp6wxOTE4Wk3/4+Pk=,tag:dk9GBIRVeTf2Btb6FxIaaw==,type:str]
    client-secret: ENC[AES256_GCM,data:uT4PICv4rrEnoOBAVk+ZxDa6G+n6SXRFbaPFwJ0TDOBHi9WwmXXgAxF1rAhuG8K0gOjfh2EUY9LlVSWWjpyVhg==,iv:k28S1FK+DyKzouLUOmz6YtZbwpV/qj4i7wzupmJ51fU=,tag:291bBavdw4qI8v40KFiYzg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:RlNaZxLJvTk6RtNodg6Dy2mVvEaqSXx/GDL1/5hp0j4=,iv:O3YlU5ndVrO9nZsQM9kv8Pkc207o8MrDezEY8Hlgyh4=,tag:VFLwphvwhvCqazr3zyH2eA==,type:str]
sops:
    age:
        - recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNmc0R2Q3QlhWRXBDbjVO
            L3dzVlZpaVIyNUsxR3V3RHE1NTdNTlVTcFEwCmVzbWgxMDl2aHRGYVoxM09DN1lp
            YzdBWDQwUVpNMG42Q3R0bXh1QWlNY3cKLS0tIG8rZ1h4OHFaTDhKZ0o1djZJbE9V
            cU13NG5BT0d2eTFKTmM5QzRuVGtmL0EKGnzbTgvNOnc9zyihWUlYMGB2zBRPdRzv
            kHxNEpL+XCDVKfjuHzBPqijfxNoVkJI1zrkVkkNe4JP+NsqS8+G8NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T09:43:17Z"
    mac: ENC[AES256_GCM,data:QGlKxYJWvwya6SlzDTISXptKKpANp2g7mAJDoS2N9TmuQAQNSSZwRT/X+C/1+XIdVuB7Sw12L+iyo/JUMlw3Ht1CNNdsm6myJgETbcc42nBV5rmpuCXs3bHmEbooNA7i3hO/+Y8dyfkDHPDyRPW+PqLzKKY31mtkbrJIK6vWsT8=,iv:zlU+9rgXyQW2h9V9Yrj0OJMJLmCD5KcNstlmTexmFtM=,tag:GltX1qY97ae8Qk9mhDB/OQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
