apiVersion: kargo.akuity.io/v1alpha1
kind: ClusterPromotionTask
metadata:
  name: helmchart-oci
spec:
  vars:
  - name: gitopsRepo
  - name: appName
  - name: appPath
  - name: chartPath
    value: "helmchart.yaml"
  - name: chartUrl
  - name: versionPrefix
    value: " "
  - name: warehouse
  - name: extPath
    value: ext
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.gitopsRepo }}
      checkout:
      - branch: main
        path: ./src
      - branch: kargo-${{ vars.appName }}
        path: ./out
        create: true
  # Clean the stage branch of the service
  - uses: git-clear
    config:
      path: ./out
  - uses: copy
    config:
      inPath: ./src/${{ vars.appPath }}
      outPath: ./out/${{ vars.appPath }}
  - uses: copy
    config:
      inPath: ./src/${{ vars.extPath }}
      outPath: ./out/${{ vars.extPath }}
  - uses: yaml-update
    as: update
    config:
      path: ./out/${{ vars.appPath }}/${{ vars.chartPath }}
      updates:
      - key: "spec.version"
        value: ${{ vars.versionPrefix }}${{ chartFrom(vars.chartUrl, warehouse(vars.warehouse)).Version }}
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: ${{ task.outputs.update.commitMessage }}
  - uses: git-push
    config:
      path: ./out
  - uses: argocd-update
    config:
      apps:
      - name: ${{ vars.appName }}
        sources:
        - repoURL: ${{ vars.gitopsRepo }}
          desiredRevision: ${{ task.outputs.commit.commit }}
