apiVersion: v1
kind: Secret
metadata:
    name: kargo-api-admin
    namespace: kargo
type: Opaque
stringData:
    ADMIN_ACCOUNT_TOKEN_SIGNING_KEY: ENC[AES256_GCM,data:d0H1z/MKVhRTkfB89jeWgoq52uQE4GyBb4MyVPvjH8w=,iv:UPpQDNyjzo+Gei+RIhAen7a8E7jSlxDclbuvMtZ/3f4=,tag:hiO1yNBWh/E9IVqrWIUZDA==,type:str]
    ADMIN_ACCOUNT_PASSWORD_HASH: ENC[AES256_GCM,data:AB4M8eecIfpu7YqXcGpsrW1ATe0BU4hPSkp6mv6bU314306LGvjw0ny9ka90mQNJSeiu30m/6XQy9DMa,iv:br4OaNxiwfXImbAEgPZbNmFGkPBVzmcOPd2cw94mv6o=,tag:RSAcQ3g1eJ1HAEO7nYCfWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdFd3Y2ZyaDVtcGtZZDgr
            QUhld2ZxZEZ5UUpTeVZ3NkZnQmFOaHVXVkdBCmJudUZHSjIwTmEvSkhCNmlSSTNp
            TUc0ZTBnazQ4QVFqa2xoT3FlMXBzelEKLS0tIFNxbFhoZTVJQVdJNGgrbVFFZlpL
            UVZLaU45OWZPb2xQT0ZUcVowTHNsanMK0y8KLQ0Y06EutmO3B37Fix4Rwp3e+O7b
            spPALW5G3L92y5+clH6uKzazBBomitcG5ewnZP4GBTJfxoQGvEdN5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRzdDVUs5UDYxNW5BaE82
            NDBjT1NPdU9hZ08wTFpRRVBINm5LdXVxRjIwCm9jRytPQWlJWXFKZGFCZG00UlVN
            b1pxTDF5aXowNWFLZENDWjJrb3p5clkKLS0tIE92L1NSWUhiTWVpeTg3aUtDa1pH
            N0k3TUVYbUlxKzRrdHROTUVDUisrSzgKHRXG4KmV2KdtF48gxuLbFfQ6QrQjDj9n
            lOSUN4qL0BW+wbZCLj0rQpbjRwtt4/3F/Gk8CYqZmChErlg8HK/2mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rt8t5r7qv3lqad907pxg9233x2xlvr5kvqc8tj38y560ayd8ruhq352jgy
    lastmodified: "2026-08-08T08:57:48Z"
    mac: ENC[AES256_GCM,data:+XPlhcUws/P695masYbSAePV9QmhIGoFjmYMgeF7cxgJYByfzcJdHBAxFNcsHNslMv0fYlrxpe7qWi82fhgmWjVlYaiEldwYycTuqRkGGACgB6Db3BHPe8pMVt50rjJMQyLX/R6vJs+EmtUlIYgR2rZ9KSfms+PUWg4ZrtGooJo=,iv:aA0znD7stGn8EqpkskbKkGjPDvqtIVyB1aL5oLleD2Q=,tag:2JoHphjSjAuPKi+KCujPyg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
