apiVersion: v1
kind: Secret
metadata:
    name: kargo-dex-env
type: Opaque
stringData:
    DEX_BRAMBLE_CLIENT_ID: ENC[AES256_GCM,data:UCH4m8c=,iv:LPH8SN3YlJSrph+iTZh0CXCSMzl719RRb5CUqeha2HE=,tag:xQHucA6OF2b9pbdSyxlTgQ==,type:str]
    DEX_BRAMBLE_CLIENT_SECRET: ENC[AES256_GCM,data:iV+xQ5IhDjhtP5fS1BRktg/Lc2m6knziyVk5Y81DyMY=,iv:S/QNwWQBoiWDGrgIidlO6qi7j5agpZ7oCAdIdTm8VUs=,tag:cpJxcYsTpt3tP976sE5TVA==,type:str]
    DEX_TWK3S_CLIENT_ID: ENC[AES256_GCM,data:rpBb4UU=,iv:lDmXPNpQaGOyqu+zKYUyOexJ8VP5e+4vxXY9SjV0TFs=,tag:Sblgy0+9iZ31mXcu6Kkj0Q==,type:str]
    DEX_TWK3s_CLIENT_SECRET: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITW5MY2dtdXVzNGNqbGJm
            ZHFyVisxWUdUeFBTUnFsenFLaXkwZ2kweG1BCng3VHp6WWN0NDhBQWtBL3FXWGpv
            WjFNU05lNkdKbkFLK0ZHNEJrdHVldTgKLS0tIGZrQ3FmQXZ5Um1LK2JaYzVaelJG
            S1pETlpaS3JmVC9sVlZ5d2tjeTlkRmcKHpuugudMrxQNBiTKHQc3PhZ7avnheGkA
            tDrZ0fgs8Jtz4R2aXl/FgL5J3CUch1aKMf+qZFrU6TP39wTenkVi6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRndJV1NyVHo1ZDY3cG1w
            K0JXc1VBVEVOODNScjd5YzRSWVlrU2NWSVFjCnJKYkRTeGFsZWw1bnRGU1dPc3Bs
            M293N2dZR2J0V2FGSXpZSldXYjhMbGMKLS0tIDJMd0VpWlNWcDVUYTRtdHdUT2l4
            V0RMZEU1eW9heTlCRnIxa0xEOHZUOUkKGbHXOBdxU1Razjkhx7U9JiwyQ2O7gTdj
            TJ0iQMA80dIi4we+C9Ahh4PZpMJnpCW8tMdwP85fzoPwl2wGc+N7Jw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rt8t5r7qv3lqad907pxg9233x2xlvr5kvqc8tj38y560ayd8ruhq352jgy
    lastmodified: "2026-08-08T09:12:43Z"
    mac: ENC[AES256_GCM,data:Fs2xyXIiNlR0ovmJ0fcQ33UQNOC/p4bU0+8Xgaiupp+IEU/1t5IEA3+0KVvqNiROZheIYSQCpUv/7M7AinHh2er7SURLzt9PqvYDTl+nnnDLs8CG24Jo5jDU4bcr1D1leZkgzOJrm78ag/4uPbeq1C5mSZc5gzY8YxbIKa5jgmQ=,iv:Hy3a7VN2FhHP8LjPLbkboBIUUaUlZepl24pBAeildBk=,tag:/U9Cx5/KaQhar8S+7K1pfw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
