apiVersion: v1
kind: Secret
metadata:
    name: n8n-postgres
    namespace: n8n
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:jkPYzmQtOHKx40QABYucjAQYaKvo9SeYZf2ZBoh5No8=,iv:YpbrEGt6kdMLyLBA/NwQ9EjTP6bgpV9QslkErLlCo3A=,tag:Uhx8LXhWlP0alncJT/zXGQ==,type:str]
sops:
    age:
        - recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbWsrQndwdjBrQUtvUUhX
            cG0zcEhJZzQvRlRmUCtxRmd0UG0vQzlvUkZnCjhseGVLbzBJYm8rNFNrV1lIanRR
            aGxDcHJWdnFaYjhhYnZXaWsveENQY1UKLS0tIEljYWVvZXNTVktmWUl5UHNpamNT
            aGJCeldIdXR3Y3Nsa0tPSkJvR09GTTgKPcjXanuCVtZUqux0TC2wmdfjmtEXLDwX
            GGt/hXWeeHSH9uc+qHRpJX+TcQlJVsF/BdRAq+Vo7xRRAp5+0sPoNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T18:36:43Z"
    mac: ENC[AES256_GCM,data:ooZTov3MIm0bTbcArl3YHl8LVRf9UThhltlef0Hlu7mo/z+w0NlCKSXzww+MV1Wg1/3gKOIxIeraZRDJBydDIAoJumv9wKMOESil0v3td8ziqNeVTCTD7PruJDmf7BCk2DEWra8spK/HGKKinxOhV1k0ZWRHbx+vCkvY7FXhmAs=,iv:+kpWpcK39nSkPR/+omwp2qroYlHcVvEcBMtxIcKc/Fs=,tag:mznn9ioTLdBaUBctzvYt1w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
