apiVersion: v1
kind: Secret
metadata:
    name: n8n-env
    namespace: n8n
type: Opaque
stringData:
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:srPjH5D721erA7JfTQUYk/E6n+Wc88oK0TJ8jyDEd8g=,iv:2HklfCk/yMbCTma29kvtx6NFOl9OAJDAzV4O9WAZXjo=,tag:5POrRBMRQlTeG78rDTm7ig==,type:str]
    N8N_SMTP_PASS: ENC[AES256_GCM,data:DiOPejp7F/7iV/STSor68JapM670huevNV4uradu6U0=,iv:jHeOUDzNuoDtaWRqB0yxYz2TNlbLT6gViEPkS/r84Wc=,tag:zB6UqE4SIe9jGiM+HH4bUg==,type:str]
sops:
    age:
        - recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTjRTUnU5VFVjM1ZabGp0
            V1J6SFJ1cUVrR0MvM1l3Zm80MUFtNGtja2xJClNHaWZmNVVMYUVzL0RsNlQzTm52
            OUhjMFk4STJXNEwvZDlnZEVUR1N2MXMKLS0tIHFtMEdXN0w5Wk84NkpiaHVJVU8x
            cnNRTVNzNWtkYzZCZjBTNzlENnFSSVkKRbbRwkhbK9VYteyh3VQfTHAg0kNORuxS
            lFtPUCRGHg6GOt03SbClkJvBtQIxA54kv3683zn/mIiL0PsURlAvWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T20:23:42Z"
    mac: ENC[AES256_GCM,data:tsiwQCHnOp0uHA2VwhzOz5gqhMcmto6iAsK+6j2fPKxTxWHY7JWOO/54+lNs1Rk4RwbWce11RYT6vodC83TQmI9I6B5GNwn+0Ij/+x15DaMiWtgr71ujUDZvZnA/ca60tbcZv0Xskwg+IgEcgYqnrRdmVvrKQ+XASFXv68GTOsQ=,iv:iTszDwZ24T9xBbRgTEP5cxrfGmi9DQy+Rh2thBKa5WM=,tag:y1FjimdtjkLRdZA4d8Mu9w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
