apiVersion: v1
kind: Secret
metadata:
    name: n8n-postgres
    namespace: n8n
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:jkPYzmQtOHKx40QABYucjAQYaKvo9SeYZf2ZBoh5No8=,iv:YpbrEGt6kdMLyLBA/NwQ9EjTP6bgpV9QslkErLlCo3A=,tag:Uhx8LXhWlP0alncJT/zXGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWN1dKMDFNUm9aSS92ZGNO
            V0JHbWl5a2lGSksxNUZ4L09rbFl4UnFVMm1zCnRNMCtRSy9wRHZLM0tIc3k1TDR3
            Ui9vNWo3RlVmNWJqZldLZWprMkZpNDQKLS0tIEEwSklFQ2dQTG5mWFIxRHloWDRz
            VEQzd09IcEplMkVSRVF2SndXN0ZWY0UKIUfO34MvlZZRWvRi3348kRvNp550FRi6
            fi2uDrlCzm33EJhXq14iRDSALOYuRUHYf2WDxTbCjF00JHwVrJbV0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3S0lPZU9uSWFDbm4vTTlX
            dVREMEpVQzZ0NnhmdkQ0UzN4TkE0Tmd2ZGpNCm5VUUlEeEhDUUFaMy9HSVNVWU1r
            SWViUHB0eklIdy81aXdjanM5TllUTGMKLS0tIFloT0tqMmNZRnQ2ek5mT1k2alE4
            ZllxUHpIOU8ySlVXV252WTZOTVVSOGcKUgIOX156oDGTzizX4rOeM9ZWysSso6+f
            +A4aWbaQ9orWeoZXekG46jIl6tHMaVLY6VdPwIJV7w9tMOXX29dbuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rt8t5r7qv3lqad907pxg9233x2xlvr5kvqc8tj38y560ayd8ruhq352jgy
    lastmodified: "2026-03-18T18:36:43Z"
    mac: ENC[AES256_GCM,data:ooZTov3MIm0bTbcArl3YHl8LVRf9UThhltlef0Hlu7mo/z+w0NlCKSXzww+MV1Wg1/3gKOIxIeraZRDJBydDIAoJumv9wKMOESil0v3td8ziqNeVTCTD7PruJDmf7BCk2DEWra8spK/HGKKinxOhV1k0ZWRHbx+vCkvY7FXhmAs=,iv:+kpWpcK39nSkPR/+omwp2qroYlHcVvEcBMtxIcKc/Fs=,tag:mznn9ioTLdBaUBctzvYt1w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
