apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homeassistant
resources:
# Generic resources
- ../ext/middlewares/
- certificate.yaml
- gateway.yaml
- ns.yaml
# Homeassistant
- configmap-homeassistant-env.yaml
- httproute-homeassistant.yaml
- httproute-homeassistant-local.yaml
- statefulset-homeassistant.yaml
- service-homeassistant.yaml
# Esphome
- configmap-esphome-env.yaml
- httproute-esphome.yaml
- deployment-esphome.yaml
- pvc-esphome.yaml
# Matter server
- statefulset-matter-server.yaml
- service-esphome.yaml
- service-matter-server.yaml
images:
- name: ghcr.io/esphome/esphome
  newTag: 2026.8.0
  digest: sha256:5ca1a7e39926cdf3cd48239ec5c9f5b429c9ac84390bd940c26c296d3cecc72e
- name: ghcr.io/home-assistant/home-assistant
  newTag: 2026.8.3
  digest: sha256:14931c6b13756317849f46da1d01b45937a1150db66c081cfe529d48215943fe
- name: ghcr.io/matter-js/matterjs-server
  newTag: 1.4.0
  digest: sha256:54232d0d3e7dff5a54759469d2753399270412b4c30c55b31750a4595e4cb236
