apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-esphome-config
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
