apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
images:
- name: quay.io/keycloak/keycloak
  newTag: 26.8.0
  digest: sha256:b0f60d489d51c5d113390bdf5461d4c06e6051be026c05549f2e1e10ec352bcc
resources:
# Dependencies: infra
- gateway.yaml
- httproute.yaml
- httproute-local.yaml
- certificate.yaml
- ../ext/middlewares
# Dependencies: postgres
- configmap-postgres.yaml
- statefulset-postgres.yaml
- service-postgres.yaml
# Main deployment
- configmap-keycloak-env.yaml
- deployment-keycloak.yaml
- service-keycloak-discovery.yaml
- service-keycloak-admin.yaml
generators:
- |-
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: keycloak
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ksops
  files:
  - secret-postgres.enc.yaml
  - secret-keycloak-env.enc.yaml
