apiVersion: v1
kind: Secret
metadata:
    name: keycloak-env
    namespace: keycloak
type: Opaque
stringData:
    KC_DB_PASSWORD: ENC[AES256_GCM,data:rN2caetf0AxdBzcVa5lewUOsZHZQ295MTYCtXobs1Dw=,iv:j7wdug3R60nSzMCDHWaVDDpoh0MmMMT5vGFM9Us4Pr0=,tag:RHn+MJeJE11yXiAmipqHYQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWU1xWjNmUHZQUkZYR1ow
            NDZsczdpb242eXZIM0ZUWktPRlZMemxQQlZrCjI3alY3U0Rmc3JoNjRVVEhkaCtF
            UDhyM2N2ZVV1UHhZV3haTGFXS3d6ZFkKLS0tIHdEM0QvYlo3bHl1cUNSL1hSU1BT
            VVJnZm5XWFJBZmF4SWdQbzB2RTdOcDQK7AFkWI08XRnPJBHb4cA2BrS/aAz61Q27
            21DlEGBbFqGbJEQ4T24NTkhNzsk87lc1XB6yIPuUImzmXYJYqBNeSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVEwzb0Q0a1grUUZkWmlM
            WG1sOUxjOUpHYU9TZlVUOFZGODg5NGtCUTFrCjd1R0hXMnUzKzJ3cW5RdFRXbHFB
            KzVjMStPcktUNGNhZkJHYzdpU1gyQUEKLS0tIFpWaFp1K3o1MmdHVlBqWFp6TmFH
            WDhSSkYrK3dtcEZacngzdWphcWR1K28KjPjuRb2NM8/pmEJZc9T8fay4i5ZzLzPs
            oB1Jhd8iGb2T4h0NphVRdIbsWT6J4KrTy7mRcLaTn6v7vu1K9FC/Vg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rt8t5r7qv3lqad907pxg9233x2xlvr5kvqc8tj38y560ayd8ruhq352jgy
    lastmodified: "2026-03-15T07:56:07Z"
    mac: ENC[AES256_GCM,data:/+glgsjeoPNHljnY+iikNoOfZ/pDQ3isyELbFXI4q3dUqO2A+4mv+0/+W0s2Cv5WfD+SqF1KyqxuYu6E+FDKwLgesprYBpLdCCflSBiJHjSDJhmen929w6YHZqXYDsEIm9XGHnqd8/V/QVBOi8v58EvgleWTTmsG+DiI/DstOcw=,iv:248L5bfzZfvRBDVuU0BnxeT0IJ/ph/w7vosQ9135AFQ=,tag:Vr8+BOC4w9B+vt4kZ3+IFQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
