apiVersion: v1
kind: Secret
metadata:
    name: keycloak-env
    namespace: keycloak
type: Opaque
stringData:
    KC_DB_PASSWORD: ENC[AES256_GCM,data:rN2caetf0AxdBzcVa5lewUOsZHZQ295MTYCtXobs1Dw=,iv:j7wdug3R60nSzMCDHWaVDDpoh0MmMMT5vGFM9Us4Pr0=,tag:RHn+MJeJE11yXiAmipqHYQ==,type:str]
sops:
    age:
        - recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTjRTUnU5VFVjM1ZabGp0
            V1J6SFJ1cUVrR0MvM1l3Zm80MUFtNGtja2xJClNHaWZmNVVMYUVzL0RsNlQzTm52
            OUhjMFk4STJXNEwvZDlnZEVUR1N2MXMKLS0tIHFtMEdXN0w5Wk84NkpiaHVJVU8x
            cnNRTVNzNWtkYzZCZjBTNzlENnFSSVkKRbbRwkhbK9VYteyh3VQfTHAg0kNORuxS
            lFtPUCRGHg6GOt03SbClkJvBtQIxA54kv3683zn/mIiL0PsURlAvWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T07:56:07Z"
    mac: ENC[AES256_GCM,data:/+glgsjeoPNHljnY+iikNoOfZ/pDQ3isyELbFXI4q3dUqO2A+4mv+0/+W0s2Cv5WfD+SqF1KyqxuYu6E+FDKwLgesprYBpLdCCflSBiJHjSDJhmen929w6YHZqXYDsEIm9XGHnqd8/V/QVBOi8v58EvgleWTTmsG+DiI/DstOcw=,iv:248L5bfzZfvRBDVuU0BnxeT0IJ/ph/w7vosQ9135AFQ=,tag:Vr8+BOC4w9B+vt4kZ3+IFQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
