apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgres
    namespace: keycloak
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:jmalPcaCZ5RkCABsmMyGl1l/3KgevekAqi2GWkO75wo=,iv:WtBvXVmGP18F8pmQeS4CYHNYp/mo6hLXFJlp9APA1Pw=,tag:5oA7r+OwtbraMon2pxE55w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTjRIOXJxS3FKaWtDdExD
            QzIvQU1tb2JSdmxFQko5NW1rQUVCYVhTc1ZBCnFvQmNxempZcHViKy9WSFV0K3hR
            VGpDNWE0NjA1RGZQNCs3NUc2MWFqRjAKLS0tIFBTcTlRQi9GUXkvQ3owZVJ3WDg3
            eTdIWVA1UGJCY0pQbGdyc2dZTHoyZWMKLO7Cv3GDO3MLrMKQ1+zSfE44mwr8GMLs
            cNv4Ze9+iGLkIpK7j2aFI07QY8onTiIinW7SrrMaq8mON9LTTcBHXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINmtGSmJ2RWIwMGhCRkR0
            Rm00NXVqVG9vY2JPZEdvVitLd2YyWi9zTkNNCk5QMG1GbFBXWC95UGlVemdGeW4y
            WUhMV3FpczlMSHFIUmZ2SlVJTEc2djAKLS0tIEpjQU5hNkNZQjF3QTRpTy8yVXZi
            dlcvY3JycnJQdHh4MzFGdldvN2dOQjAKbynFU7z/pIg3OpHa/0Ls993nTxttq/47
            awXjGOrAbsvFRsQu94R9mh9aEsWFBPl5OuvkYcuGfL1N/x4cUA4QlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rt8t5r7qv3lqad907pxg9233x2xlvr5kvqc8tj38y560ayd8ruhq352jgy
    lastmodified: "2026-03-15T07:57:30Z"
    mac: ENC[AES256_GCM,data:PIqkRafppjntHNqrGi4CsbqTJiPGmZLTGHZJujhsYt8HN+zGrBQ3H0/MwIL1F/KL1qHtSONRcn78dNl9Yo24wx1pC+Va2cz8Zb3JZeFMSjVUA7at8/iKt8WBTd6iJqPgPQYAqKb8aQ4IgBbXf1vM4Ztrkgn6OpzA/BergX6q13k=,iv:dGFjqrVBzzhQCZ2jt+kfm4UH5CbK/fozK5NBCHhpooc=,tag:01FQpGpJVfRs642n+clQeA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
