apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgres
    namespace: keycloak
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:jmalPcaCZ5RkCABsmMyGl1l/3KgevekAqi2GWkO75wo=,iv:WtBvXVmGP18F8pmQeS4CYHNYp/mo6hLXFJlp9APA1Pw=,tag:5oA7r+OwtbraMon2pxE55w==,type:str]
sops:
    age:
        - recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbWsrQndwdjBrQUtvUUhX
            cG0zcEhJZzQvRlRmUCtxRmd0UG0vQzlvUkZnCjhseGVLbzBJYm8rNFNrV1lIanRR
            aGxDcHJWdnFaYjhhYnZXaWsveENQY1UKLS0tIEljYWVvZXNTVktmWUl5UHNpamNT
            aGJCeldIdXR3Y3Nsa0tPSkJvR09GTTgKPcjXanuCVtZUqux0TC2wmdfjmtEXLDwX
            GGt/hXWeeHSH9uc+qHRpJX+TcQlJVsF/BdRAq+Vo7xRRAp5+0sPoNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T07:57:30Z"
    mac: ENC[AES256_GCM,data:PIqkRafppjntHNqrGi4CsbqTJiPGmZLTGHZJujhsYt8HN+zGrBQ3H0/MwIL1F/KL1qHtSONRcn78dNl9Yo24wx1pC+Va2cz8Zb3JZeFMSjVUA7at8/iKt8WBTd6iJqPgPQYAqKb8aQ4IgBbXf1vM4Ztrkgn6OpzA/BergX6q13k=,iv:dGFjqrVBzzhQCZ2jt+kfm4UH5CbK/fozK5NBCHhpooc=,tag:01FQpGpJVfRs642n+clQeA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
