apiVersion: v1
kind: Secret
metadata:
    name: secret-k3s-server-scrape
    namespace: observability
type: Opaque
stringData:
    scrape_configs: ENC[AES256_GCM,data:p9lfYcY+lIIulT00BElt13kLNb1vOoFbOA0Da0aQ0b33EisECAfwH9+97IouCi+mJFc9coI1IttWmvRfnE/TN1FMmmAWbujUxWYVVlGMsYW6jctGpgsw2+CJUr8aS/GIAq0XIh7LNDCqXMKL+BRtG+lV94g5qWtjN2nVP2OMJ+TxvjakLOf4z7fdcuOODGmL55pl28JkJ26n7HGI+tMGyqxe/mimvk6tHz+tpwMyNT5s1Xy0giYBRcrgk8yc/8mkHByB9D30g6nEUm2ZtP6n4VmbqOynm3Go+bt9D+U4Rk9ZPlN/U7mIyiEGbOF1myWF7vcaDTPv7spLZX0cLqtpO7RKzLOBakHh1FZAnU3BaiQomuLj9EmXczBzdWsYSQVzbKvolLehWcZub5tT7GU/7ZHc+vz4W3G7n4eKqZuLJ7E9sZUGc4BQ37r3VkK/Lqg5p2taA6kedGS3denOw63Ry+4SebSVPRLthzwEhg7cY5LpCSUKoyZTeH9JgFKhx4Egoql/Xth9lxh8x3TU4wJiJJUjguXxC4vrj+NLk4dhwTtdqF1wScV2WME87dRl0IM4fBmLb08hemDkbxz0kz9s0750U12SgLmcA0s2Twf2rGu1LmEGPwVchU9LxuzMYUbE+VZOCKzYIqouZDiUVGtREqS+9LmJOaVNIazkMtXeISZgA6YSpb2ZigbGsXA8gx5zGwqgkK/S/5WqZaF2q0ZMX/viWSifN5Tn9NgWf0PfGzGmMJFk+TC0jKPTNhUW2B7X4ztPuYfgtj5ebStnADbvH9cSGhEFlqUi5YI7W8yFCvrdKFHKSpEasVH4PdkVoISbwego9Njr1M/PJ6WJYYZRuzg7rbAFKOXWEz8M6W62A6WOYmB7a5W9SubZwNISF/0=,iv:p8rt7PZCFynazOkJupgH2l96NnupXlLC1pYzvpiZXl0=,tag:HH25SVWEq+H0YmRAnQojkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSCtOMGd1aU91UFY0TmN6
            VzNXUVQyUlNMNHRaUFU2Sm5vUUZkTTkvaEVZClJOLzF5QWtXV2lldmNjdlRGS1hT
            SkNlZTlMckJyeWY3RHhtYjNwSnVib0kKLS0tIGJsb0YrQzJVcjd4Qjd6bTRhZmRF
            eUVFRTlUR25Qd2JwU3Z2azVyVDZKZXcKqrAejIH4TulMQjOQFIiTb+dxlAyBDNo8
            88avv05PH34CQkG9FCjG6VadU4W6wnx4Wz4xq/RVdxXdbU2LXNorAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
    lastmodified: "2026-05-24T07:17:45Z"
    mac: ENC[AES256_GCM,data:eYr9B+CxL/aOmb/f/zkRMCgnxIg1oQd6vtshHSBMd/iUdd0SeZjmLlcrATob5ZStODLNTbt8uKPZ7bPZhAZMcsptIO5pTOFbh3wnq7afJA2wZrE7kSEfCvUeU+qdXpjCcyB03sulIXBiAmCmDiqVUI3/nQcvEToId5DraStz6ew=,iv:krPRGfJ1TCvTaPIFM9YiEAd9B3mxqSzrRqpFYSh7KSY=,tag:U8H7DIllS1H46IBxZrPoqQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.0
