apiVersion: v1
kind: Secret
metadata:
    name: grafana-env
    namespace: observability
type: Opaque
stringData:
    KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:cTQuZrS0KESBOyOuAtlh19rfMW+S2EZRNp21zrCBXUA=,iv:dwV4Cr6tOplfToPOAEwslGeKN1Nm7I29DtvUQC8pEW8=,tag:2VjvjXrqL1CcRnTHz2xwxg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:JlcAUAWikjv+IE5c5yB7YdJgQvVZe4JIY/34gUKQaSeeN1/uVlJZGg==,iv:gHhiSkv+J8jONxwFFedAEp2JgxVIDAgwGv1W8qnGKiw=,tag:YjNx3/QEZ+vPasNXVl3H7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma0tra3VkYjlMTzJvV1lW
            Uk5KM1hiYXM3eFRFeVlTdE85aklyTGRtdjBBCmkzdS9KeUNDSWNLZ2dhZExMRzEw
            WkQwVTQ0WWlRY201UFVhRVQzWVIvK1EKLS0tIHNIaVB0Q0g2N0tXQ05GTXdiNnIx
            ZWhDVXdwNGpJM3hBN25oYVpTRjA3cUUK3xUYVOKhF3rj1LsZtDYKwo+IDEwyvEV7
            7QaV+o6GqVBuXaJEaf+X8qrtACLaIX1s6ziPefeV0/g+s3jm+f6Gmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
    lastmodified: "2026-05-24T07:17:30Z"
    mac: ENC[AES256_GCM,data:a1WGaoOWjJ3/QmrldfBaTLa4+OEp08IPPflpwTRoIwCtPC8aymqBmE2k14NFciIky8es+ZAniFYRVW3EUhRRxsr8lY+qKRpGKdLSAQAUpOq1WVcAR1vjxDYxZEE9ssRIt1RLe2OPpxwCl2YlHPKZioNVcjnl7Av6wGK7KS014eQ=,iv:jYD995cyln1A8tbY38RPi2dHuPAeSODgCOgeobo1GwU=,tag:/sg+RhelwVP0VaJ6gtfxXg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.0
