apiVersion: v1
kind: Secret
metadata:
    name: secret-k3s-server-scrape
    namespace: observability
type: Opaque
stringData:
    scrape_configs: ENC[AES256_GCM,data:5iMdeUj7zJvtZAM07C4Yc9gAn1sP4OQsSMaUO9pkQ5ZN/sllTRgbmVxnJVWqfwAr/Zo4L4MvWuHwiSv8Q1nbsqZAO4xgnAjaLIrQhpJg1Z4RzzHcnCiuCbnAfbJAxkn5n47oOcLXHNkDXQ1P1JUObL+CJDUlWj5fRO9bHC9Xs+KCbyfzcOyNOhbQhLuFYLq62nCKGYoC70yFCP9Up18L2cNK/dBL4IVkmn+LFvbI5SqeD+sfR0OVbm3MN6TFmo/ouWU+Ahr3On0FPveRulVELE0BRPLwaaqgicbBJFNEEOX0zA61ibO0d5IvhMyuOXknmnhHoUQDnOBveTeCzXrcd/0QnQ9s6EQAvk8hxLJBHTMTvOvehnodgNey3L+qEYoj7LiB819DFuiyCKOfFWAZuiWdlwGMVW50ddnq7elLyv8/Oes6D2xQZLKRvt1o9oETt+lj0cFFaLjj6IpJ5fEv5eyfljbAycihJZ6oInR1W6u2XZZHfqkwUbz/sQNnhhfTmIw3U+GjcT15I05iUrXt2UWaXcWB4i+hng4JfWmni4ACnLD9+g99T79JWIuKkxMx22Bx/JLDmD/FD0sbE2Eck08PdVzudoP2S6HwdyBAtwJMURgEIeLQCu7dfM0SHy+494Jwp6FkhvL6LXXVkZDfsWOtcg8D7zAQvGXypp3ypm0lEUnrohZLKLwdnAobZ8eBfVmKbbwDRhDEfomloO4G/RfbL7ipSXwwTqntY6u8q7SKfZeTuVILHww9um/nCebZvhE3jHdqY7iXKK1dPh1I1SXQhOCPGGEMQllHjGqctt2FIDsoNwebFqiHEulEpgYCuKIgsmhzDAA6vjaZcUh5kn9A3CGwf2xrnTbn6l8b8fO+cQ7Y0h0U5srkPCfeKVU7HS2nzOeWpwj9/JW/GHa9do8QmO1wrEVSB12/+nuzofw20ZneSb6464+5nO3YAqOOZfTBLkCQqu8Uv9jBQ5cdVGZ/D/O6pm6wMM/uIuY3jZn2KpCxx7d+BZjjcfl2TZ77n1xUoVPrQunlbQ3S78Hge/B1ca7VBCqyOqN29Pecc3EmA/YQvapX/SBjFBVCIz0oJ0lRt6feP/79GhgGVcoCSeYG18TmBkxtaIhkcWZD6w4Gq7uXNnGSO9q5gjVEOnVf2b/oVDeWbtHNE3j9YfzQd1mZF45291DL4rI1D9OZpTho2pGgcoJjAAN+o0fuqTYFM6ly/yGp8BAxvQ==,iv:VvOSrcgCWyXVjUOpv4peXNRDzv30TrYd+HZT24xPXKo=,tag:Y5+TWpg6fHD7hIlXmcRjYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSCtOMGd1aU91UFY0TmN6
            VzNXUVQyUlNMNHRaUFU2Sm5vUUZkTTkvaEVZClJOLzF5QWtXV2lldmNjdlRGS1hT
            SkNlZTlMckJyeWY3RHhtYjNwSnVib0kKLS0tIGJsb0YrQzJVcjd4Qjd6bTRhZmRF
            eUVFRTlUR25Qd2JwU3Z2azVyVDZKZXcKqrAejIH4TulMQjOQFIiTb+dxlAyBDNo8
            88avv05PH34CQkG9FCjG6VadU4W6wnx4Wz4xq/RVdxXdbU2LXNorAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
    lastmodified: "2026-05-24T13:10:15Z"
    mac: ENC[AES256_GCM,data:PHydXz4wGVy5AvU3wVMzQtf9sKp93TaRssozP4Qp3MWEj9c6yo046S6w9/7u/kZKRi9WsbXB6S66iIQw7lJDyzs6qaUMwgxADu5qtH0rsyV8ER9MJbOP/kXqbb9PzH3aYfS1LrqUn6Hj2MkxAWsuMFIu/KkGrwfi6pf7Mze/8ls=,iv:PljM+MxQz/kVbSvW51vl+oXBkpf0/ybIfb+QCxQq56o=,tag:fxAfpacAwfJXZj702IOzfg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.0
