apiVersion: v1
kind: Secret
metadata:
    name: grafana-env
type: Opaque
stringData:
    KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:cTQuZrS0KESBOyOuAtlh19rfMW+S2EZRNp21zrCBXUA=,iv:dwV4Cr6tOplfToPOAEwslGeKN1Nm7I29DtvUQC8pEW8=,tag:2VjvjXrqL1CcRnTHz2xwxg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:JlcAUAWikjv+IE5c5yB7YdJgQvVZe4JIY/34gUKQaSeeN1/uVlJZGg==,iv:gHhiSkv+J8jONxwFFedAEp2JgxVIDAgwGv1W8qnGKiw=,tag:YjNx3/QEZ+vPasNXVl3H7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma0tra3VkYjlMTzJvV1lW
            Uk5KM1hiYXM3eFRFeVlTdE85aklyTGRtdjBBCmkzdS9KeUNDSWNLZ2dhZExMRzEw
            WkQwVTQ0WWlRY201UFVhRVQzWVIvK1EKLS0tIHNIaVB0Q0g2N0tXQ05GTXdiNnIx
            ZWhDVXdwNGpJM3hBN25oYVpTRjA3cUUK3xUYVOKhF3rj1LsZtDYKwo+IDEwyvEV7
            7QaV+o6GqVBuXaJEaf+X8qrtACLaIX1s6ziPefeV0/g+s3jm+f6Gmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
    lastmodified: "2026-05-23T18:59:38Z"
    mac: ENC[AES256_GCM,data:KTCpuLJxPqSIzX+3qRsbd3PUtcmf6+HvmN+iuUyWsRh6riLSI/FYmUfsZJmnTr1gr0+/TUvEjL38AHOzkoj9GNtV41Tl5q+YKBxfHI/Q0AEXGzzALzWhBiFfEel7sHNnkP0GyBzwE6mcEq/xIc/yhXO9JhlC6N3KpgW0SWRKhZU=,iv:wVbPtKj15QG+y80WAnRHu6iKz7MD6XGknc4Erd2rqa0=,tag:b0rVAB9wRzlKN1aM17kMDw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.0
