apiVersion: v1
kind: Secret
metadata:
    name: grafana-env
    namespace: observability
type: Opaque
stringData:
    KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:cTQuZrS0KESBOyOuAtlh19rfMW+S2EZRNp21zrCBXUA=,iv:dwV4Cr6tOplfToPOAEwslGeKN1Nm7I29DtvUQC8pEW8=,tag:2VjvjXrqL1CcRnTHz2xwxg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:JlcAUAWikjv+IE5c5yB7YdJgQvVZe4JIY/34gUKQaSeeN1/uVlJZGg==,iv:gHhiSkv+J8jONxwFFedAEp2JgxVIDAgwGv1W8qnGKiw=,tag:YjNx3/QEZ+vPasNXVl3H7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOEJ2L1ZTRkVMSGs5MFZx
            S0lraDBPK1pNQk1UbWpzTStmcEl6K2U1MFNBClEveEhYV1NraTBpTGwvbi9sdVEv
            azkycG9aeTMzOUpWcWFYZ3ZpZHdpU0EKLS0tIGNyc2RNMHFuTHJPTVNCSE9DQnNL
            bXUwMlAxRjJ0TTY2TEU5NkZZaEp2TkkK6luQWu+VKjbxl4wq0e9GOXOj6tJfBizg
            RCKT/SvS1oBwSj/ErhYOE+7pB+GT2XSfPQ4xkW+BaggZm6Vwf/XIKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRzZuM1JXSTdFSXZyTkY5
            ekJib3RlbHRDRWV2L2F5M1ZGMk9lcXFEaG1zCjhUL0wwSnVjaTRrMVpIc3ZWZ3Iw
            aGtDQzNSRi90eFYwSyt5VyszOVkrbEkKLS0tIFBKNlJsUkJsUGVqeEtVR1BIblJN
            aHVwaEJkZlNrZjVXRitzZXk3Q2lzUGcK61tEDXeNxTALqYN8HN8jYTuG3YxBPlMK
            5v9Tt5owzVRMZ2r2vNquOhMVL/d9nMKAWxDRGKKyzMeXtUg8R6wCQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rt8t5r7qv3lqad907pxg9233x2xlvr5kvqc8tj38y560ayd8ruhq352jgy
    lastmodified: "2026-05-24T07:17:30Z"
    mac: ENC[AES256_GCM,data:a1WGaoOWjJ3/QmrldfBaTLa4+OEp08IPPflpwTRoIwCtPC8aymqBmE2k14NFciIky8es+ZAniFYRVW3EUhRRxsr8lY+qKRpGKdLSAQAUpOq1WVcAR1vjxDYxZEE9ssRIt1RLe2OPpxwCl2YlHPKZioNVcjnl7Av6wGK7KS014eQ=,iv:jYD995cyln1A8tbY38RPi2dHuPAeSODgCOgeobo1GwU=,tag:/sg+RhelwVP0VaJ6gtfxXg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.0
