apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kp-bramble
spec:
  promotionPolicies:
  - stageSelector:
      name: glob:live-*
      matchLabels:
        home.bramble/allow-auto-promotion: "true"
    autoPromotionEnabled: true
