apiVersion: v1
kind: Secret
metadata:
    name: bramble-git
    labels:
        kargo.akuity.io/cred-type: git
type: Opaque
stringData:
    repoURL: ENC[AES256_GCM,data:8S1S4c6fDuBE1v0mk9DIJlSZa8E55O6d4FsOwxYNM4PcXw==,iv:WYJlQb2uYlp+j7ii2EKu0x1aums+OxNX0wR0mUeO+E0=,tag:2x6hU8i59O8ilKYyea9rMQ==,type:str]
    username: ENC[AES256_GCM,data:9Cty,iv:mhweD9WyOqTtYqlJNA0nAb3dLwLHtcTHdqe8VNPFJyk=,tag:Xo48Q1H1e3bUowuSYrEREA==,type:str]
    password: ENC[AES256_GCM,data:AifspitdGEaWIp1VzpJq0PkepgA2eWILPrs8zYhYeE5J0vl+dYRgbrp6kLuCKDy90c078Y91LcsbWr7LsDnBReE1G4W+o4+d2ifs9Ypi97OT98endPQW2l2dPlYb,iv:MADOgfuSnP0K8Ye7d0YCfFcd9yCwnpQsH5sLnBqyMf4=,tag:HFb0VXZYsGL24BKXrr7A0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RHB5VUYwQ1BDTldQSXBz
            RlJOeW1JSHVVRXJBUXQ4d3hBbktuTk1OeUJjCjlVbDJCNzltU2hJZGFMWGxLTWw4
            QlYzd3JaOHF3djVmWlIxTUNYeW96cjgKLS0tIGZnWmVNMGZuRXBKNVpYRTF1VzUx
            dUNoOGVBRWlLeENoRXlMNjRkcGJrWWcKt+MX9TyCrwOaD9u+eLaDgVOpdo/Dl+wc
            3qvpjngddSoivFCd0crydnvWUtskAbTxffrHXi/TSs+70LIaugQYGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWDZJRVdhM3hQWUNxdWMy
            b1dPTER2MUlaMlRKWjU4dk1mOWdkMlpJT0djCkRNUS95WlRuSlNKWXQyNkcvcnV6
            YmlyRUdkUzBFNDgyS0RtaW5qZTcwZmMKLS0tIG5FV0hVSmxvVjQ0bTBqUUJ1bnNH
            NVp0T3ROb2hzTkFMcExKYU5Rbk9ERHMK97cvElq0jBx46ZsH8iOlo3vMjuowB8/u
            MrGNPKrlw1lmZ7h/y70xXSX5h7F0fwb6HbWKi0T0dFwTysTSJxcqvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rt8t5r7qv3lqad907pxg9233x2xlvr5kvqc8tj38y560ayd8ruhq352jgy
    lastmodified: "2026-08-08T13:34:07Z"
    mac: ENC[AES256_GCM,data:aDqa4EHw8adel3t7PxJAwgB0aF+7G59qSLmaXzmjc4cyLtzxqbuMFcyRkGTsc0GbrfHCKXFzShFr72lqdYcmGSZ0FKAu6+N26vvIe3j9CQcRtJ7fE3acNrIkgKusDMo60g2kLvy3AFFRnOtv7ZQxswoC7whlfOmlvIeGnktg7zY=,iv:ReMTDbdzW+TxFtcrmk+RTR4sl4JLgfJoP3c2/+YPb4Q=,tag:zRCb1P9I+x1RDXwbq4yxbA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
