apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: live-headscale
spec:
  vars:
  - name: appName
    value: bramble-headscale
  - name: appPath
    value: headscale
  - name: gitopsRepo
    value: https://github.com/b-n/bramble.git
  promotionTemplate:
    spec:
      steps:
      - task:
          name: containers
          kind: ClusterPromotionTask
  requestedFreight:
  - origin:
      kind: Warehouse
      name: headscale
    sources:
      direct: true
