apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo
spec:
  subscriptions:
  - chart:
      repoURL: oci://ghcr.io/akuity/kargo-charts/kargo
      discoveryLimit: 20
  - git:
      repoURL: https://github.com/b-n/bramble.git
      branch: main
      commitSelectionStrategy: NewestFromBranch
      includePaths:
      - "cert-manager/"
      excludePaths:
      - "glob:*.md"
