apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kp-techwerkers-k3s-services

resources:
- project.yaml
- projectconfig.yaml
- stage-live-discourse.yaml
- stage-live-docmost.yaml
- stage-live-espocrm.yaml
- stage-live-excalidash.yaml
- stage-live-gancio.yaml
- stage-live-keycloak.yaml
- stage-live-listmonk.yaml
- warehouse-discourse.yaml
- warehouse-docmost.yaml
- warehouse-espocrm.yaml
- warehouse-excalidash.yaml
- warehouse-gancio.yaml
- warehouse-keycloak.yaml
- warehouse-listmonk.yaml

generators:
- |-
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: kp-bramble
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ksops
  files:
  - ./secret-techwerkers-git.enc.yaml
