apiVersion: v1
kind: Secret
metadata:
    name: bramble-git
    labels:
        kargo.akuity.io/cred-type: git
type: Opaque
stringData:
    repoURL: ENC[AES256_GCM,data:pA24B0p5+HLGF7QlwUf0l3KFg8V29XiA9wA+t535cgHsOsQqfpjDjq63XtM10Q==,iv:Y9ER3Q01VeBD8RaNicMZW5yaKLIEyg/LJQGNrwn9HdA=,tag:g4fSridaYZu3eAonU7IXBQ==,type:str]
    username: ENC[AES256_GCM,data:/6b8DGjEjHv/Iwx8dyYg,iv:bwxSX/OU3RwTDaLqcUsRU5sDw9lGWWz/G+ENHaJxf3Y=,tag:wZCYO8YWFszxCEr8ORpCFg==,type:str]
    password: ENC[AES256_GCM,data:GOPGjdxnKs0IwzoLL0oHC+/wNYLQHZPs5hH969anq13PGRpUX4ehyg==,iv:n9nhWTaTi6zMAV8fWOuXkF0TQxzci1qXRR1GjEqbUH4=,tag:1eBxpH7euyJ2RLo0twd/iA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RHB5VUYwQ1BDTldQSXBz
            RlJOeW1JSHVVRXJBUXQ4d3hBbktuTk1OeUJjCjlVbDJCNzltU2hJZGFMWGxLTWw4
            QlYzd3JaOHF3djVmWlIxTUNYeW96cjgKLS0tIGZnWmVNMGZuRXBKNVpYRTF1VzUx
            dUNoOGVBRWlLeENoRXlMNjRkcGJrWWcKt+MX9TyCrwOaD9u+eLaDgVOpdo/Dl+wc
            3qvpjngddSoivFCd0crydnvWUtskAbTxffrHXi/TSs+70LIaugQYGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWDZJRVdhM3hQWUNxdWMy
            b1dPTER2MUlaMlRKWjU4dk1mOWdkMlpJT0djCkRNUS95WlRuSlNKWXQyNkcvcnV6
            YmlyRUdkUzBFNDgyS0RtaW5qZTcwZmMKLS0tIG5FV0hVSmxvVjQ0bTBqUUJ1bnNH
            NVp0T3ROb2hzTkFMcExKYU5Rbk9ERHMK97cvElq0jBx46ZsH8iOlo3vMjuowB8/u
            MrGNPKrlw1lmZ7h/y70xXSX5h7F0fwb6HbWKi0T0dFwTysTSJxcqvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rt8t5r7qv3lqad907pxg9233x2xlvr5kvqc8tj38y560ayd8ruhq352jgy
    lastmodified: "2026-08-30T19:37:53Z"
    mac: ENC[AES256_GCM,data:V5V1teNJjRsn8tjl+NAqa539qeOqQeJ9+gHwWbSwmPjwBZ+4kd5e2tsxUlExyIT17tfbH0NFumuUpfwuHHNfmZeHdn+H1+m07ymrDLyYH6xXKik7z7Vt4lAnFuRyF5eAP36NzE2s6rrJCqFu/vCS7rrC4ghb+yAU4npuTYEsz3c=,iv:2vfvFiXwRdsubJaa8XS3HS9gdeQwb8yy/XQJIH/2F40=,tag:Zj13/PLJcQ18Le6FM/PpQg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
