---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  repo: https://oauth2-proxy.github.io/manifests
  chart: oauth2-proxy
  version: 8.5.1
  targetNamespace: oauth2-proxy
  createNamespace: true
  valuesContent: |-
    config:
      existingSecret: oauth2-proxy-dex
      configFile: |-
        # OIDC Settings
        provider = "oidc"
        provider_display_name = "Dex"
        oidc_issuer_url = "https://dex.bennaylor.dev"
        email_domains = [ "*" ]

        # Proxy Settings
        reverse_proxy = true
        # ForwardAuth mode
        upstreams = [ "static://200"]
        real_client_ip_header = "X-Real-IP"
        whitelist_domains = [".bennaylor.dev"]

        # Cookie Settings
        cookie_secure = true
        cookie_domains = [".bennaylor.dev"]

        # Header Settings
        pass_user_headers = true
        pass_authorization_header = true
        pass_access_token = true
        pass_host_header = true
        set_xauthrequest = true
        set_authorization_header = true

        # UI Settings
        skip_provider_button = true

        # Other Settings
        silence_ping_logging = true

        # Logging
        request_logging = true
        auth_logging = false
        standard_logging = true

    replicaCount: 1
