apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
images:
- name: docker.io/valkey/valkey
  newTag: 9.1.2
  digest: sha256:c123e3715db63d06d4ad6964884037aa0d5d4d703939b9929954112889708e1d
- name: ghcr.io/immich-app/immich-machine-learning
  newTag: v3.2.4
  digest: sha256:e16c2f166a8174901959fdf85e2e4c7bd1ebc4b37e0b6655de97c41408a260c4
- name: ghcr.io/immich-app/immich-server
  newTag: v3.2.4
  digest: sha256:d317916b28090c33eb36b308464ea391f8b7df1d850fcfea227a39ec879718c2
- name: ghcr.io/immich-app/postgres
  newTag: 18-vectorchord0.5.3-pgvector0.8.1
resources:
- ../ext/iscsi
- ../ext/middlewares
- ns.yaml
- certificate.yaml
- gateway.yaml
- httproute.yaml
- httproute-local.yaml
# Postgres
- configmap-postgres.yaml
- statefulset-postgres.yaml
- service-postgres.yaml
# Valkey
- deployment-valkey.yaml
- service-valkey.yaml
# Immich
- configmap-immich-env.yaml
- deployment-server.yaml
- deployment-ml.yaml
- service-immich.yaml
- service-ml.yaml
# Backup
- cronjob-backup.yaml
generators:
- |-
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: immich
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ksops
  files:
  - ./secret-postgres.enc.yaml
  - ./secret-immich.enc.yaml
  - ./secret-immich-backup.enc.yaml
  - ./configmap-immich-backup.enc.yaml
