apiVersion: v1
kind: Secret
metadata:
    name: immich-env
    namespace: immich
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:E2oESqLCh7fJ2IlKU+jD75OeT0STOqhN7DzzI1J5cvkXIvEWEadQR5UOmEYdCn6qlnOGrm11UALVFi5xMMXB/Q==,iv:B5z53hqKC8Nxv3u3Htom6YFG8Q/N4X6Peas+xmqRSHA=,tag:s7LcBweI9a1eAFvYBPWX2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNkY1RWx1WTk2VyttNzhn
            R0dmR0pKbHdFYW53dWxKY1Z5eG1ZcnVuZkhZCjVXRmpRSXlCTnM3Nkc0TWppa3A1
            emJUMEdjeGhja1lRdUxXMXJuc2Qzc00KLS0tIGV1K1BCUzdJSFNKdlAwdWx4V1k3
            WEFDZXJ1dDNJTXBKY1Z4WnNreTZjVkkK2qNq/UU+omcMV83vGjg3yGT2Y/mI1eNk
            zm/o11jwksj0Z5PWfeMM8hBxMJtQcfhe8fD8TZunJM1JMCyGci/8Tg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReXpFc1JUd3V2VVBPS3R2
            U1U2MkJIREtVVjlVdlAxS09jWVFOQ0dvc1RnCmljd05UaFBUOUpEV25tbTA1Zlk1
            WmRrV2JkenJHbytOcUxVczNNcEx3SFUKLS0tIGxTLzJNV3lRN3R6cjl4Qlh6N2JX
            ZzlkK25MUEEyaXRyc3JnNnpsMnpzSkkK5ZKdLk2MQI/TgpfljVsjFhimxNcndoFZ
            KwqNmKRhwX9f9A6gg+pUe18zuH35qNZI09eW8dPlS0pN5d3MmXjmXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rt8t5r7qv3lqad907pxg9233x2xlvr5kvqc8tj38y560ayd8ruhq352jgy
    lastmodified: "2025-12-02T13:55:42Z"
    mac: ENC[AES256_GCM,data:h5aOcGngohv34el6GQAMKfAiIp3ywtb271ZsiG8DFRjoNDFOJwRUH1D2UeXRJVmxvuP45yRjqFDIovHcuzN/kWAgyY3biXf37s9Iac9KvRGAQoHVQOQYNDGm20XgbBxg0v8jrxLX3e0p5cXeQhbbaOLlH+E61f7K47VnVjVUYJ0=,iv:7b95RYcwa6IcH+2+Cq1SuTR4YqXN+N2Tvxan/lLeOEw=,tag:Dhr23E/RlaK6wZ/D8HeFzQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
