---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: adguard
spec:
  gatewayClassName: traefik
  listeners:
  - name: web
    port: 9080
    protocol: HTTP
    hostname: adguard.home
