---
apiVersion: v1
kind: Service
metadata:
  name: adguard-dns
spec:
  type: LoadBalancer
  selector:
    app: adguard-adguard
  ports:
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 53
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
