apiVersion: v1
kind: Secret
metadata:
    name: headscale-headplane
    namespace: headscale
type: Opaque
stringData:
    cookie_secret: ENC[AES256_GCM,data:zWFprQ3i0MP6qYIJW/Jj4o3uHOx9kCxohUGwkPtqKww=,iv:SxQU6usanSiXS4XSE7cxNuiLmML9mXMjGdQzL6rU0vI=,tag:KQSgbdWB/CAZVZ8QiX+0aw==,type:str]
    headscale_api_key: ENC[AES256_GCM,data:3/ennrAd75y5W7i6kwe7pV+Gkn23/hYqZ9PgRl4ZBswZ7VOXjZB26iSZ2FRQtaeiad3Hp6EJgBrAIbNAvyjsE/VCv+nIAMO2wmv1Q4+5rHVuYJOUBdcH,iv:im2s9Ax8ZVa5dxmjcV5G0oXe5BMzM+SVQLdF4uVacWg=,tag:OEXgoKrldCujNotZDldTSg==,type:str]
sops:
    age:
        - recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVV1p4NG1Pb0h0OUNoeUZN
            RG1yQmRQSmNvOFZRQUhQRzIyZWtFU2Nid0FNClBPSGR2MnMydnRBbVNweERTZkQw
            bFdjNGtYTWlodVhsQ1Q3MUVIay93ODgKLS0tIFFINDV0OEh1RzhUSW81U0VnTzFT
            R2hpenZobGlJWXlPOWdvalVkNXR4WDgKmNYip8vZSMInOMnKAyoLeeqvBY9AivRu
            nIKFyBylTkIIVTnHMMOpgHDiGe+pltRvO17FwRojITsJiaN/ljbkWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T11:54:31Z"
    mac: ENC[AES256_GCM,data:/LConu2T/xwH67bX2eAB6ejusqpZHJFMtZiAPTK9383cYzEB5rIKwYOFNuiy55eDCNwXd1XwVUwlpi/x/lpTsz1HCDnOGQl0Q6xC3loWM7lQOH0wZJ/oDQolvc4lc6U20oekAMQxLEITtsodRJgP/ok6HjWgEuR8XqM244/IqVk=,iv:iIeewSVDHFRnVsLW1EfNQHwkrPx/It9kQmh2crU+d80=,tag:GGbHrbz2DQoKavleeV/aYw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
