apiVersion: v1
kind: Secret
metadata:
    name: headscale-keys
    namespace: headscale
type: Opaque
stringData:
    oidc_client_secret: ENC[AES256_GCM,data:waSSTzG+ovVtGTEb8mQsz4rN87vcV9h+WW5lw4dHmZc=,iv:tCufdQfCc8P3ghvKj//6JTF9CzXaGm5gBAWl2vP3wqQ=,tag:qk1LO+3vYmzUPJcJl1fKCg==,type:str]
    noise_private.key: ENC[AES256_GCM,data:kXxSx8ncUHIOg2kGIwFF682nPcdC5fBsaWYC8pZWXNHXRy5XoWpQs6tfWUY=,iv:95c52EZ7qsoRnhPpzm5IJOFfSrxfOM6zPHjJYsGbmdQ=,tag:Aio0ggJsMRS2jjwQA3yfrA==,type:str]
sops:
    age:
        - recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4QXVkallzcjVMOXhvYThr
            N3ZpTlZOdG01dm0xNE9sV2xvSEwrRU9EenhBCmVlbU92VHVMUFkxZi9YbkJIL2do
            cDZaeE5CY0srN0FpN2d5enk4Z1loRDQKLS0tIERrSk5tZW5tVElRZ2syd2Nhc1Rj
            dmxMdXg5TEFKU0pHOEJSZUFXMWFNUFkKj4OV0wcGAAgHqaTsRjNz51i7cCbAHfvh
            GJeuNv7QWZvaRxYKkVdnpP5TC4BK7VcxbTdBtj205FlOIc4io/U6BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T09:17:40Z"
    mac: ENC[AES256_GCM,data:QzmcWnP1NCpe70hb/o4irK/LzqmYi5I30Y2yi8TZdYgYJH4N+KgzxXLijKiAsriDYrFqhqOw83+kuQN3A2j4aBTrsspz1nwB8rhmX5M6ITBxrsSsjZrQyK8K/TW20wLYFyB0ncYu8niiMdpwojlh3wOtF07PtgkQ/uh6nxbKeK0=,iv:GFWeU6SvfemQGqrwhrMNRM2CmE69IQeln46OzgadHGc=,tag:f3+oe7cHMBiyhQRiSgHoKA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
