apiVersion: v1
kind: Secret
metadata:
    name: headscale-headplane
    namespace: headscale
type: Opaque
stringData:
    cookie_secret: ENC[AES256_GCM,data:zWFprQ3i0MP6qYIJW/Jj4o3uHOx9kCxohUGwkPtqKww=,iv:SxQU6usanSiXS4XSE7cxNuiLmML9mXMjGdQzL6rU0vI=,tag:KQSgbdWB/CAZVZ8QiX+0aw==,type:str]
    headscale_api_key: ENC[AES256_GCM,data:+u2uvri/e1+T0WTLByMypp9jfVppX3E6Qqd/zdgO1ssahzfw2bHa89YqCmEt9rvIIu49MUhJJzX6/zz/vzd414QH3XgQ++CQ1dz80LBj5nyXvbKTHeLV,iv:+eA9cnQL1EobH5m25sOW+n0VM/4KHXiChV4mRgGsHjI=,tag:9rKKByIJLnzvLXNGj1iisQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMendnMFlCb3hCaG5EbzY1
            WHlqU096RnMvYmFwelVzR2JLUmY2RXhWalJVCnRuWGhsKzJ0VFMycjFlODhkRUQy
            TnZxenpzemZEQXpmandrRDcxYkdCUEkKLS0tIFlyMTRUR1pmNEVCZnFvZUZuSWd2
            enltTlV4Ull2dllpQ3p4TkQ1cnBTMEEKvQgyehkMA7wD+k30DOZl67G8j/Mqd/wV
            6QcYvm3vO9g2Mlia3euwzauKw5GyY7BfeVW2OHHpJqH/jk4CHxZ0Vw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVldSaFlqN1RWZ3BwdG1l
            VFR5c2M1SmRmd1ZFTDhDNEVHSXhWTVRSRzJ3ClVkbHVpK3I2Zkx1a0VDbTN2SzJ1
            UTNrUnFEYjNCMU1od1JyT3hiQ25RSXMKLS0tIHM0Y1ZNVzJ5bVZpZWQ1MkdFWE94
            N1lxbmwyamVNemlFb0FCbGJndWNiR0EK6oj9gB2CtNyfGNGx4rt3w5fzTHVhcvAs
            +NApKpEHPEICw1WXWgFi1suJiDw37Ab2m3C//+qIvpgOctH1YJkc0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rt8t5r7qv3lqad907pxg9233x2xlvr5kvqc8tj38y560ayd8ruhq352jgy
    lastmodified: "2026-06-24T06:54:00Z"
    mac: ENC[AES256_GCM,data:Ev/2vbxjdy+ys5oNXdLtl4hbhwliUsMZOTHlQ3QLicfNNSJ8V6Zta9hh/yApt/ZkHvL827MPPk6XN+ex1qrJX9RxxKaGV1hvfKzQH/NGjdI34oGaOcIIEGjsm/QGDTjCGRaxFyZOJU/Vv44orfiZiiyVMsirhxws0nCodxgKQxA=,iv:QJCmhL1Pqw7t8+25URr8Itrp2eaaXjrZjfpK9YYD/Vs=,tag:XsIyQ18M95ctl4eWps3R5w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.1
