apiVersion: v1
kind: Secret
metadata:
    name: iscsi-chap-secret
    namespace: kube-system
type: kubernetes.io/iscsi-chap
stringData:
    node.session.auth.username: ENC[AES256_GCM,data:SucWVGaOsg==,iv:rmYvzOM7KsuF5gkf4GKwbAldQ4rpeL6ESpbJbh6paL4=,tag:ySTCvNyUW8AULC59rDBdmw==,type:str]
    node.session.auth.password: ENC[AES256_GCM,data:A24TSJg8Vcc1AF37,iv:0I26jCgQblUjAvqeJPeOFR1XJXI6s+XhQCdNbivYDVU=,tag:og6ugwOR+vNDVuW0BgVWfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRVpLT2hTSjgvZEZweUZq
            OWRrWDRtNG9pY1p4VWdtcGZib0pFNHVoR2dzCjZIa2hnNWYydnFxTEZuM3lwVU5s
            NThOWXJncWdmK3FBSTNyNDNsNFdWbVUKLS0tIEtselQvb1JUZ2hYWER2cDd3SFF4
            S0hUK1gvUFhtQjQ3SEpkNVdYcEJWL00KIfdyCwRN5rKqA/dHa6XUdKO3djTuIyjr
            G2XZXYTm6GRCWJ/h69PS72A4lD/YFUhZHuqjuN49tbsYx23/Ri+Msw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUnBtR0lFaFUrYW1nOUVN
            UXBIU20ramVaT0F5Z21vY2hwSlROUjhjVnhvCjcwd0haOHYzQVNJQ0VzUFo1Rkxi
            bzdPL2dWQkh6QU5hTWtCaWg4K3JHZ1kKLS0tIHJEUFgvL0RRb3dNU1prNDM1Mkdq
            dkJvZ1pTN1B5ZkZHT3dvTjNJOGV2d28KrCTeKXNrfIc9ngzhY+JBJ/wpXHG9hQSV
            HYdR6a21Nza3H4brPEDoja6NBk/AanoFXfMhAw1/YU2iVesC+1HisQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rt8t5r7qv3lqad907pxg9233x2xlvr5kvqc8tj38y560ayd8ruhq352jgy
    lastmodified: "2025-11-25T11:59:43Z"
    mac: ENC[AES256_GCM,data:eHTm2FFZNd6w8EsC+zFXoHg6qAj/5WTGRZEvNDgw7/DOP6SNjQenwEERdaLyLecrnu9T0BklVmYMgTBJXZRI872s+kXTD6T6F6P4EpCK5rv0wm/UrE87oJZn0wGSrK6Cbeeayh01hW6gcciYm7d5bNcPAcsJxodW9h3leXpybD8=,iv:L34H90SKeBNLNPkxneTgGpuolTE+rq82e21WiGCAcQU=,tag:aVVHsu86gAx4AAyES/4Cgw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
