apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bramble
  namespace: argocd
spec:
  source:
    path: ./
    repoURL: https://github.com/b-n/bramble.git
    targetRevision: argo
  destination:
    name: bramble
    namespace: argocd
  project: bramble
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - FailOnSharedResource=true
    - ApplyOutOfSyncOnly=true
