apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: techwerkers-k3s
  namespace: argocd
spec:
  description: Techwerkers cluster
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  destinations:
  - name: "*"
    namespace: "*"
    server: "*"
  sourceRepos:
  - "*"
  roles:
  - name: admin
    description: Do anything in this project
    groups:
    - twk3s_admin
    policies:
    - p, proj:techwerkers-k3s:admin, applications, get, techwerkers-k3s/*, allow
    - p, proj:techwerkers-k3s:admin, applications, update, techwerkers-k3s/*, allow
    - p, proj:techwerkers-k3s:admin, applications, sync, techwerkers-k3s/*, allow
    - p, proj:techwerkers-k3s:admin, applications, action, techwerkers-k3s/*, allow
    - p, proj:techwerkers-k3s:admin, applications, override, techwerkers-k3s/*, allow
    - p, proj:techwerkers-k3s:admin, applicationsets, get, techwerkers-k3s/*, allow
    - p, proj:techwerkers-k3s:admin, applicationsets, update, techwerkers-k3s/*, allow
    - p, proj:techwerkers-k3s:admin, logs, get, techwerkers-k3s/*, allow
    - p, proj:techwerkers-k3s:admin, exec, create, techwerkers-k3s/*, allow
    - p, proj:techwerkers-k3s:admin, clusters, get, techwerkers-k3s/*, allow
