apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bramble
  namespace: argocd
spec:
  description: Bramble home cluster
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  destinations:
  - name: "*"
    namespace: "*"
    server: "*"
  sourceRepos:
  - "*"
  roles:
  - name: admin
    description: Do anything in this project
    groups:
    - bramble_admin
    policies:
    - p, proj:bramble:admin, applications, *, bramble/*, allow
    - p, proj:bramble:admin, applicationsets, *, bramble/*, allow
    - p, proj:bramble:admin, logs, get, bramble/*, allow
    - p, proj:bramble:admin, exec, create, bramble/*, allow
    - p, proj:bramble:admin, clusters, get, bramble/*, allow
