---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v3.4.6/manifests/install.yaml
- appproject-bramble.yaml
- appproject-techwerkers-k3s.yaml
- app-bramble.yaml
- app-techwerkers-k3s.yaml
- gateway.yaml
- certificate.yaml
- httproute.yaml

patches:
- path: patches/configmap-argocd-cmd-params.yaml
- path: patches/configmap-argocd-rbac.yaml
- path: patches/configmap-argocd.yaml
- path: patches/deployment-argocd-repo-server.yaml

generators:
- |-
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: argocd
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ksops
  files:
  - secret-age.enc.yaml
  - secret-argocd-dex-credentials.enc.yaml
  - secret-cluster-bramble.enc.yaml
  - secret-cluster-twk3s.enc.yaml
