apiVersion: v1
kind: Secret
metadata:
    name: argocd-dex-credentials
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    DEX_BRAMBLE_CLIENT_ID: ENC[AES256_GCM,data:tYhKk6Kk,iv:KT0pQqtD3AQDh4nX+3/JfxSF4TOjOiiQd6770uvMUSc=,tag:6tdBO0pR0R2501JIpQPACQ==,type:str]
    DEX_BRAMBLE_CLIENT_SECRET: ENC[AES256_GCM,data:KJ4q/uqOsf5hXcDMugG2wlorFxXjkGrjsgLDJyJCXY8=,iv:ur3H8YROadYQlYnwrA+LUgZjuGDaaMTAald4GEbRVKI=,tag:QI2zBscp4okaSLtOk/tv5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RnYzTVMyaUFYZ2FLRFdM
            MWdHNXRyKzBGWkxEMElRQkdSUlBTR2lTY1VvClpTaUJKRzMrRExPcm9EM3BKS0hT
            VGVnRDJ1TERJcnJjSkNFa05TT1RBOE0KLS0tIDI1TlE1aGdybjdyWFNMcndrNWRv
            elZOY3lhaTc5OGhVamJxd1BteC9KYjgKIzkmzWLJgcaCKBJh1gNSp11a3B1W3pO0
            KOXWqq848gi0a9NO0gZMkgmwLdJdPqUn63U0e+NjA+4WV2QALB0GAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSDJ4UEVyeEhTbGVrYXRy
            RktnbXNiTFdybk1pWHNYeTVncVZhd1RxWURzCm1rTmVXMHREeXh5QVgrZHhpUmJD
            bWZRYThZZit4ZTI5NzRSWkxDKzNUNFEKLS0tIGVhTTNSREJBMUJOSTZQUFB4SnFp
            OCs4ZmFkRVZlRnNoWTVBdEFjRFFlUUEKEJoimbJWvzKXPhPt4TNz8QgB7WSuHZnJ
            4SUXGMQTScfprdL4F75TysJu0vv+jY1FUoJn8xtlWg8S1KQlQEdapw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rt8t5r7qv3lqad907pxg9233x2xlvr5kvqc8tj38y560ayd8ruhq352jgy
    lastmodified: "2026-08-02T09:18:46Z"
    mac: ENC[AES256_GCM,data:oMABcsAE4UpgLyKxBgv72Pc6CMsuMKqhcjO5tbrFf7lGXp4wDaVkOvdsReVzCt6U2nrqK+3IxBWTBaNjX9LzSARScw5L/wmrEcDk4QK2zsq5FPDaPmcN1S2LSYpJY9z/dgnL9osllUByIODlzvpDFA7aTsiROHXUBnypbOgC5p8=,iv:8CNF/nZqDBb82NTiI3XMd63nQXs0PgNM9es7oxQSmhw=,tag:WDOHoWGMEoMRB/aVfyYhTw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
