apiVersion: v1
kind: Secret
metadata:
    name: argocd-age
    namespace: argocd
type: Opaque
stringData:
    keys.txt: ENC[AES256_GCM,data:+K980ve0r2/tYApBfkYftn5ayN5qMa97Xg3l3HVuEP1uB5bsaM5ytBD2Yo17xmwAz1hJvndlT1QHAepqVKlxFtgVHlDgDjBnT1n8iK06VGZKpVdzzNCSWnk+0nDvBrV9v6qLaP/AtCNEVoizekm4LO33nX8raX6zeGz1JP9IZSX5/5iEvbxawVQOKN0JXEUwEo110OtlytKPIV99tVIY9CRWvKvf6XWW1xuZRVM88fLqNIwm/mzTuHWKIZLc,iv:2kNHLj6CwP6VSAqTpL1XU09ivuxtBz8rgrSoWZhCkbM=,tag:hMh3hkG+eH6pmpSTVxxt5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVkEvc1F0d1dOQTcvTEww
            eFlHa2RwV0l5VWorOC9EbzdGWUx6Y2tlTXdrCkF0N1hETXhCdVBNeGtCNWoraUwz
            WVlCa0hFbWFjVkNQWkUza0JHU1pDWkEKLS0tIDREQUtOaEZSTFF3OGw5UHIwMmxq
            R3J5Q210dUZLTmZMb3pNWGpjQkdiRVUKAzIUidEXGkKypifyKqDztGOj6z1MOs1T
            UdafINGDmwRDV07XyuX537zOffoZDiMnYs2okXzxCVsSMap0lR/ZuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSkZpQk9SOTNMUWd1SFlm
            Z205aE9pYlkrdEtQTXRJVm1MK24vb2owakRjCk1ENjFlUys5ZXg3Wkt2Z2JNN0hV
            WHRoWDRqU2tEM0dBNlUrZlJWWnBtbDgKLS0tIHM5eHMyak9USUhzYXcxczIwV3FL
            clJkS1VkWFZqYnl6TzU3ak1BaTVhZk0KNHMerj4/S/Yhng3wmzRTg2VRHIvhFYqa
            hOoLuue+kk0cCgLgH8mzJCl3+7EcImYTYWh+bK7DAjM7g0HffkcDyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rt8t5r7qv3lqad907pxg9233x2xlvr5kvqc8tj38y560ayd8ruhq352jgy
    lastmodified: "2026-08-02T10:11:45Z"
    mac: ENC[AES256_GCM,data:Rl4Wvpr1Bq8TvQRzTJeMgMAQ0VY4TBcy1vQ0itEFUDaig3Q2avnvJgmIanyuKpnnMtMZDtMI0RFf0youB3kSISm58d0kGcENWv9y1klBCiG+DrnfRaFleDIv4MOzlR2Y5R6uYTg23Gt3e8IrmKatmUz05H1WQBWKdPAUuy4hBv0=,iv:XTAUJsWyDyb1NWWYM72Y6Wt71sLo9enzxV6DIpZPtmQ=,tag:eB30Gi6IvTYvJb78dD5uIQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
