apiVersion: v1
kind: Secret
metadata:
    name: argocd-dex-credentials
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    DEX_BRAMBLE_CLIENT_ID: ENC[AES256_GCM,data:tYhKk6Kk,iv:KT0pQqtD3AQDh4nX+3/JfxSF4TOjOiiQd6770uvMUSc=,tag:6tdBO0pR0R2501JIpQPACQ==,type:str]
    DEX_BRAMBLE_CLIENT_SECRET: ENC[AES256_GCM,data:KJ4q/uqOsf5hXcDMugG2wlorFxXjkGrjsgLDJyJCXY8=,iv:ur3H8YROadYQlYnwrA+LUgZjuGDaaMTAald4GEbRVKI=,tag:QI2zBscp4okaSLtOk/tv5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVXNDdEw5bzdVZmJtNjlU
            c21hUGg5b3NkZm9yc3BMTjI5cUpMdmVnZVdJCkNMaUM2NFlBKy9iWXcvSHE3cWdz
            OE1YWE9QSWNIRHVUb1Y5OHpDN0NTYTQKLS0tIGdHOGlkSGNma2ZxaUY5M3gwVHNF
            QlNXMGRiellaYldLMklKUktRWXVQUVEKc+Jfrc1IXp0U9lfY4SmM1AA2wrYtR80D
            4Nbyisk9lWb2wqcqrH2Lj0PVyevhVhts2rs7816cblPsuZiyibhn9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
    lastmodified: "2026-08-02T09:18:46Z"
    mac: ENC[AES256_GCM,data:oMABcsAE4UpgLyKxBgv72Pc6CMsuMKqhcjO5tbrFf7lGXp4wDaVkOvdsReVzCt6U2nrqK+3IxBWTBaNjX9LzSARScw5L/wmrEcDk4QK2zsq5FPDaPmcN1S2LSYpJY9z/dgnL9osllUByIODlzvpDFA7aTsiROHXUBnypbOgC5p8=,iv:8CNF/nZqDBb82NTiI3XMd63nQXs0PgNM9es7oxQSmhw=,tag:WDOHoWGMEoMRB/aVfyYhTw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.13.3
