apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kp-techwerkers-k3s-infra

resources:
- project.yaml
- projectconfig.yaml
- stage-live-cert-manager.yaml
- stage-live-oauth2-proxy.yaml
- warehouse-cert-manager.yaml
- warehouse-oauth2-proxy.yaml
