apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kp-techwerkers-k3s-infra

resources:
- project.yaml
- projectconfig.yaml
- stage-live-cert-manager.yaml
- stage-live-oauth2-proxy.yaml
- warehouse-cert-manager.yaml
- warehouse-oauth2-proxy.yaml

generators:
- |-
  apiVersion: viaduct.ai/v1
  kind: ksops
  metadata:
    name: kp-bramble
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ksops
  files:
  - ./secret-techwerkers-git.enc.yaml
