apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: live-cert-manager
spec:
  vars:
  - name: appName
    value: twk3s-hetzner-cert-manager
  - name: appPath
    value: hetzner/infra/cert-manager
  - name: gitopsRepo
    value: https://codeberg.org/Techwerkers/manifests.git
  - name: chartUrl
    value: oci://quay.io/jetstack/charts/cert-manager
  - name: warehouse
    value: cert-manager
  - name: versionPrefix
    value: "v"
  promotionTemplate:
    spec:
      steps:
      - task:
          name: helmchart-oci
          kind: ClusterPromotionTask
  requestedFreight:
  - origin:
      kind: Warehouse
      name: cert-manager
    sources:
      direct: true
