apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: oauth2-proxy
spec:
  subscriptions:
  - chart:
      repoURL: https://oauth2-proxy.github.io/manifests
      name: oauth2-proxy
      discoveryLimit: 20
  - git:
      repoURL: https://codeberg.org/Techwerkers/manifests.git
      branch: main
      commitSelectionStrategy: NewestFromBranch
      includePaths:
      - "hetzner/infra/oauth2-proxy/"
      excludePaths:
      - "glob:*.md"
