apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: cert-manager
spec:
  subscriptions:
  - chart:
      repoURL: oci://quay.io/jetstack/charts/cert-manager
      discoveryLimit: 20
  - git:
      repoURL: https://codeberg.org/Techwerkers/manifests.git
      branch: main
      commitSelectionStrategy: NewestFromBranch
      includePaths:
      - "infra/cert-manager/"
      excludePaths:
      - "glob:*.md"
