apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  labels:
    prometheus: scrape
spec:
  jobLabel: kube-state-metrics
  endpoints:
  - port: http-metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
