apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: node-exporter
  labels:
    prometheus: scrape
spec:
  jobLabel: node-exporter
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    scheme: http
  selector:
    matchLabels:
      app: node-exporter
