apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr
images:
- name: docker.io/lipanski/docker-static-website
  newTag: 2.6.0
  digest: sha256:66a530684a934a9b94f65a90f286cba291a7daf4dd7d55dcc17f217915056cd5
- name: lipanski/docker-static-website
  newTag: 2.6.0
- name: lscr.io/linuxserver/jellyfin
  newTag: 10.11.11
  digest: sha256:4f6d8dfc53ec5a1ddf7a90e4338972d57d7b0adff6dc88b53184f8285d0b594f
- name: lscr.io/linuxserver/prowlarr
  newTag: 2.5.2
  digest: sha256:ab91301778251f82a31bbfc87f0497376d59e84439d9a1ceff6a61d594d1e3d7
- name: lscr.io/linuxserver/transmission
  newTag: 4.1.3
  digest: sha256:c85eb732f0ae9e4152b76c2d7da26e50c1fb54c05d9723800c198385ff66c247
resources:
- ../ext/iscsi/
- ../ext/middlewares/
- ns.yaml
- pvc-media.yaml
# Gateway and routes
- certificate.yaml
- gateway.yaml
- httproute-local.yaml
- httproute-public.yaml
# Root web
- configmap-web.yaml
- deployment-web.yaml
- service-web.yaml
# Transmission
- configmap-transmission-env.yaml
- deployment-transmission.yaml
- service-transmission.yaml
# Jellyfin
- deployment-jellyfin.yaml
- service-jellyfin.yaml
# Prowlarr
- deployment-prowlarr.yaml
- service-prowlarr.yaml
